baseURL = 'https://baka-op.github.io'
languageCode = 'en-us'
title = 'Baka'
theme = 'hugo-coder'
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "ScruffieBaka"
description = "Scruffie's personal website"
keywords = "blog,developer,personal"
info = ["Programming", "Music", "Modding"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2023
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

customCSS = []
customSCSS = []
customJS = []
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[menu.main]]
  name = "About"
  weight = 1
  url  = "posts/welcome"
[[menu.main]]
  name = "Posts"
  weight = 2
  url = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"


[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/scruffiebaka"

[[params.social]]
name = "Discord"
icon = "fa-brands fa-discord fa-2x"
weight = 1
url = "https://discord.com/invite/WseNACbmQx"

[[params.social]]
name = "Itch.io"
icon = "fa-brands fa-itch-io fa-2x"
weight = 1
url = "https://bakaop.itch.io/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-twitter fa-2x"
weight = 1
url = "https://twitter.com/da_real_baka"

[[params.social]]
name = "Youtube"
icon = "fa-brands fa-youtube fa-2x"
weight = 1
url = "https://www.youtube.com/@_bakaa_"